### ISSUE TITLE
Missing symbol error while loadlibrary

### ISSUE THREAD

**Issue by abyvinod** [worc4021/GeoCalcLib#1]
My installation steps were based on http://worc4021.github.io/jekyll/update/2016/04/08/welcome-to-jekyll.html:
1. Clone the git repo.
2. Create a folder `files` within the repo for INSTALLDIR.
3. Download the gmp zip folder into my home folder
4. Follow installation instructions given in https://gmplib.org/gmp-man-6.1.2.pdf.
      a. ./configure ABI=64
      b. make check
      c. sudo make install
I confirmed that I have a file `gmp.h` in `/usr/local/include` and `libgmp.a`, `libgmp.la`, and `libgmp.so.10.3.2`  (3 files linking to it, including `libgmp.so`) in `/usr/local/lib`
5. I created User.make file in my local repo, GeoCalcLib with the correct paths:
```
MATLAB_ROOT=/usr/local/MATLAB/2017b/
INSTALLDIR pointing to files folder created in step 2.
```
6. I added the following line to startup
`addpath(genpath('/datafiles/git/Matlab/Library/GeoCalcLib/'))`
This will add the folder `GeoCalcLib` and `GeoCalcLib/files` as well
7. I can confirm that `help LRS` works.

However,  `[~,~] = loadlibrary('libgeocalc','path/to/GeoCalcLib/mainFunctions.h'))` throws error attached below.

My system setup is Ubuntu 17.10 and the output of MATLAB's ver command is as follows:
```MATLAB Version: 9.3.0.713579 (R2017b)
Operating System: Linux 4.13.0-46-generic #51-Ubuntu SMP Tue Jun 12 12:36:29 UTC 2018 x86_64
Java Version: Java 1.8.0_121-b13 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
MATLAB                                                Version 9.3 
```
My LD_LIBRARY_PATH is the default version.
My PATH now includes in addition to the default, `/usr/local/lib` and `/usr/local/include`.
My LD_PRELOAD is empty.

Any help regarding the installation is greatly appreciated! Thank you.

-------------------------

Error using loadlibrary
There was an error loading the library
"/datafiles/git/Matlab/Library/GeoCalcLib/libgeocalc.so"

Missing symbol '__gmpq_abs' required by
'/datafiles/git/Matlab/Library/GeoCalcLib/libgeocalc.so'
Missing symbol '__gmpq_add' required by
'/datafiles/git/Matlab/Library/GeoCalcLib/libgeocalc.so'
Missing symbol '__gmpq_canonicalize' required by
'/datafiles/git/Matlab/Library/GeoCalcLib/libgeocalc.so'
Missing symbol '__gmpq_clear' required by
'/datafiles/git/Matlab/Library/GeoCalcLib/libgeocalc.so'
Missing symbol '__gmpq_div' required by
'/datafiles/git/Matlab/Library/GeoCalcLib/libgeocalc.so'
Missing symbol '__gmpq_equal' required by
'/datafiles/git/Matlab/Library/GeoCalcLib/libgeocalc.so'
Missing symbol '__gmpq_get_d' required by
'/datafiles/git/Matlab/Library/GeoCalcLib/libgeocalc.so'
Missing symbol '__gmpq_get_den' required by
'/datafiles/git/Matlab/Library/GeoCalcLib/libgeocalc.so'
Missing symbol '__gmpq_get_num' required by
'/datafiles/git/Matlab/Library/GeoCalcLib/libgeocalc.so'
Missing symbol '__gmpq_init' required by
'/datafiles/git/Matlab/Library/GeoCalcLib/libgeocalc.so'
Missing symbol '__gmpq_mul' required by
'/datafiles/git/Matlab/Library/GeoCalcLib/libgeocalc.so'
Missing symbol '__gmpq_neg' required by
'/datafiles/git/Matlab/Library/GeoCalcLib/libgeocalc.so'
Missing symbol '__gmpq_set' required by
'/datafiles/git/Matlab/Library/GeoCalcLib/libgeocalc.so'
Missing symbol '__gmpq_set_d' required by
'/datafiles/git/Matlab/Library/GeoCalcLib/libgeocalc.so'
Missing symbol '__gmpq_set_den' required by
'/datafiles/git/Matlab/Library/GeoCalcLib/libgeocalc.so'
Missing symbol '__gmpq_set_num' required by
'/datafiles/git/Matlab/Library/GeoCalcLib/libgeocalc.so'
Missing symbol '__gmpq_set_ui' required by
'/datafiles/git/Matlab/Library/GeoCalcLib/libgeocalc.so'
Missing symbol '__gmpz_add' required by
'/datafiles/git/Matlab/Library/GeoCalcLib/libgeocalc.so'
Missing symbol '__gmpz_addmul' required by
'/datafiles/git/Matlab/Library/GeoCalcLib/libgeocalc.so'
Missing symbol '__gmpz_clear' required by
'/datafiles/git/Matlab/Library/GeoCalcLib/libgeocalc.so'
Missing symbol '__gmpz_cmp' required by
'/datafiles/git/Matlab/Library/GeoCalcLib/libgeocalc.so'
Missing symbol '__gmpz_cmp_ui' required by
'/datafiles/git/Matlab/Library/GeoCalcLib/libgeocalc.so'
Missing symbol '__gmpz_divexact' required by
'/datafiles/git/Matlab/Library/GeoCalcLib/libgeocalc.so'
Missing symbol '__gmpz_fac_ui' required by
'/datafiles/git/Matlab/Library/GeoCalcLib/libgeocalc.so'
Missing symbol '__gmpz_gcd' required by
'/datafiles/git/Matlab/Library/GeoCalcLib/libgeocalc.so'
Missing symbol '__gmpz_get_d' required by
'/datafiles/git/Matlab/Library/GeoCalcLib/libgeocalc.so'
Missing symbol '__gmpz_init' required by
'/datafiles/git/Matlab/Library/GeoCalcLib/libgeocalc.so'
Missing symbol '__gmpz_init_set_ui' required by
'/datafiles/git/Matlab/Library/GeoCalcLib/libgeocalc.so'
Missing symbol '__gmpz_mul' required by
'/datafiles/git/Matlab/Library/GeoCalcLib/libgeocalc.so'
Missing symbol '__gmpz_mul_ui' required by
'/datafiles/git/Matlab/Library/GeoCalcLib/libgeocalc.so'
Missing symbol '__gmpz_neg' required by
'/datafiles/git/Matlab/Library/GeoCalcLib/libgeocalc.so'
Missing symbol '__gmpz_out_str' required by
'/datafiles/git/Matlab/Library/GeoCalcLib/libgeocalc.so'
Missing symbol '__gmpz_set' required by
'/datafiles/git/Matlab/Library/GeoCalcLib/libgeocalc.so'
Missing symbol '__gmpz_set_si' required by
'/datafiles/git/Matlab/Library/GeoCalcLib/libgeocalc.so'
Missing symbol '__gmpz_sqrt' required by
'/datafiles/git/Matlab/Library/GeoCalcLib/libgeocalc.so'
Missing symbol '__gmpz_sub' required by
'/datafiles/git/Matlab/Library/GeoCalcLib/libgeocalc.so'
Missing symbol 'mexErrMsgIdAndTxt' required by
'/datafiles/git/Matlab/Library/GeoCalcLib/libgeocalc.so'
Missing symbol 'mexErrMsgTxt' required by
'/datafiles/git/Matlab/Library/GeoCalcLib/libgeocalc.so'
Missing symbol 'mexPrintf' required by
'/datafiles/git/Matlab/Library/GeoCalcLib/libgeocalc.so'
Missing symbol 'mxCalcSingleSubscript' required by
'/datafiles/git/Matlab/Library/GeoCalcLib/libgeocalc.so'
Missing symbol 'mxCreateCellArray' required by
'/datafiles/git/Matlab/Library/GeoCalcLib/libgeocalc.so'
Missing symbol 'mxCreateNumericMatrix' required by
'/datafiles/git/Matlab/Library/GeoCalcLib/libgeocalc.so'
Missing symbol 'mxDestroyArray' required by
'/datafiles/git/Matlab/Library/GeoCalcLib/libgeocalc.so'
Missing symbol 'mxGetData' required by
'/datafiles/git/Matlab/Library/GeoCalcLib/libgeocalc.so'
Missing symbol 'mxGetField' required by
'/datafiles/git/Matlab/Library/GeoCalcLib/libgeocalc.so'
Missing symbol 'mxGetM' required by
'/datafiles/git/Matlab/Library/GeoCalcLib/libgeocalc.so'
Missing symbol 'mxGetN' required by
'/datafiles/git/Matlab/Library/GeoCalcLib/libgeocalc.so'
Missing symbol 'mxGetPr' required by
'/datafiles/git/Matlab/Library/GeoCalcLib/libgeocalc.so'
Missing symbol 'mxGetScalar' required by
'/datafiles/git/Matlab/Library/GeoCalcLib/libgeocalc.so'
Missing symbol 'mxGetString' required by
'/datafiles/git/Matlab/Library/GeoCalcLib/libgeocalc.so'
Missing symbol 'mxIsChar' required by
'/datafiles/git/Matlab/Library/GeoCalcLib/libgeocalc.so'
Missing symbol 'mxIsComplex' required by
'/datafiles/git/Matlab/Library/GeoCalcLib/libgeocalc.so'
Missing symbol 'mxIsDouble' required by
'/datafiles/git/Matlab/Library/GeoCalcLib/libgeocalc.so'
Missing symbol 'mxIsEmpty' required by
'/datafiles/git/Matlab/Library/GeoCalcLib/libgeocalc.so'
Missing symbol 'mxIsScalar' required by
'/datafiles/git/Matlab/Library/GeoCalcLib/libgeocalc.so'
Missing symbol 'mxIsSparse' required by
'/datafiles/git/Matlab/Library/GeoCalcLib/libgeocalc.so'
Missing symbol 'mxIsStruct' required by
'/datafiles/git/Matlab/Library/GeoCalcLib/libgeocalc.so'
Missing symbol 'mxIsUint32' required by
'/datafiles/git/Matlab/Library/GeoCalcLib/libgeocalc.so'
Missing symbol 'mxMalloc' required by
'/datafiles/git/Matlab/Library/GeoCalcLib/libgeocalc.so'
Missing symbol 'mxSetCell' required by
'/datafiles/git/Matlab/Library/GeoCalcLib/libgeocalc.so'
Missing symbol 'mxSetM' required by
'/datafiles/git/Matlab/Library/GeoCalcLib/libgeocalc.so'
Missing symbol 'mxSetN' required by
'/datafiles/git/Matlab/Library/GeoCalcLib/libgeocalc.so'
Missing symbol 'mxSetPr' required by
'/datafiles/git/Matlab/Library/GeoCalcLib/libgeocalc.so'

**Comment by worc4021** [comment]
Could you please run 

```
ldd /datafiles/git/Matlab/Library/GeoCalcLib/libgeocalc.so
```
if the result looks sensible, could you also run it from matlab, i.e. 

```
system('ldd /datafiles/git/Matlab/Library/GeoCalcLib/libgeocalc.so','-echo')
```
it seems that for some reason the loader is not able to locate the gmp library and matlab's libmx.

**Comment by abyvinod** [comment]
I got the output
```
inux-vdso.so.1 =>  (0x00007fff2954e000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f03a183b000)
/lib64/ld-linux-x86-64.so.2 (0x00007f03a1e4f000)
```
while running on my terminal as well as in MATLAB. In the MATLAB, I got the output system.

**Comment by worc4021** [comment]
I have changed the build to now use Matlab's mex command for all interface functions. This simplifies the build across different platforms. I tested all functions on Ubuntu 16.04 as well as on MacOs 10.14 with Matlab 2018b. I will update the website to describe the new build.

**Comment by caohaiwen** [comment]
Dear Dr. Schaich,

I'm a Ph.D. student from CUHK, Hong Kong, and I'm trying to use your Matlab interface. Firstly, thanks for your contribution to building this Matlab interface. 

However, I encountered some problem when I'm trying to run "startup.m", which said as follows,

Error using loadlibrary
There was an error loading the library "libgeocalc"
libgeocalc.so: cannot open shared object file: No such file or directory

Error in startup (line 5)
[~,~] = loadlibrary('libgeocalc','/home/charles/Documents/GeoCalcLib/src/mainFunctions.h');

Caused by:
    Error using loaddefinedlibrary
    libgeocalc.so: cannot open shared object file: No such file or directory

(I'm using Ubuntu 16.04 with Matlab2018b, and have installed GMP 6.1.2)

I'm looking forward to receiving your response, and thank you for your contribution again.

Best Regards,
Charles

**Comment by abyvinod** [comment]
Hi Charles,

The installation instructions have been changed recently. See the updated README on the repository.

Can you try this or its variant?

1. Download the zip file from  [https://github.com/worc4021/GeoCalcLib/archive/master.zip](https://github.com/worc4021/GeoCalcLib/archive/master.zip).
1. Extract the contents of this zip file to a desired location, whose full path is referred to here as `/path/to/GeoCalcLib`
1. Open a terminal and change directory to GeoCalcLib by `$cd /path/to/GeoCalcLib`. We will refer to this location as the GeoCalcLib root folder.
1. Create a folder `mexfiles` in GeoCalcLib root folder. 
1. Create a file named `User.make` in GeoCalcLib root folder using your favorite editor with the following contents, and save it. See [https://www.mathworks.com/matlabcentral/answers/66570-what-is-the-default-installation-path-for-matlab-on-architecture-x#answer_78163](https://www.mathworks.com/matlabcentral/answers/66570-what-is-the-default-installation-path-for-matlab-on-architecture-x#answer_78163) for hints on how to identify your matlab root folder for your OS.
    ```
   # Specify the absolute path to the root folder of your Matlab
   # installation where <FULL-PATH-TO-YOUR-MATLAB-INSTALLATION>/bin/mex 
   # exists
   MATLABROOT = <FULL-PATH-TO-YOUR-MATLAB-INSTALLATION> 
   # Path to which everything should be installed
   INSTALLDIR = ../mexfiles/
   ```
1. In the command prompt in GeoCalcLib root folder, execute `$ make`.
1. Add `/path/to/GeoCalcLib/mexfiles` to MATLAB path. If you want to use this across sessions, we recommend adding the following command to your MATLAB startup.
```
addpath('/path/to/GeoCalcLib/mexfiles');
```

Regards,
Abraham

**Comment by caohaiwen** [comment]
Dear Abraham, 

Thanks for your detailed suggestions.

 I think I have found the problem, which is that Dr. Schaich did not update his installation instruction resulting in the inconsistency with the updated files.

In his updated version, there is no need such open shared object file and no need to load any library.

Best Regards,
Charles

**Comment by worc4021** [comment]
Hi Charles,

Sorry I didn't respond earlier and thank you for your interest in the geocalclib. 
I'm sorry for the confusion. The build process for the interface has changed recently and I seem to have messed up the website accompanying the solution. I followed the instructions of pages.github.com to update it, but the page that is actually linked is half messed up and not updated. There is a 'new' folder in the repository 'docs' which is registered to be the source of the page, and it is updated. But as you can also see, the page itself does not reflect these changes. 

So, again: My apologies for your inconvenience. I blame github pages ;)

Hopefully Abraham soon succeeds in developing a purely Matlab based build for all major platforms, then the installation difficulty would disappear.

All the best,
Rainer
